export const LABOUR_ROLE_OPTIONS = [
  {
    value: "general-labourer",
    label: "General Labourer",
    baseRate: 28,
    hoursPerWeek: 40,
    kiwisaverPct: 0.03,
  },
  {
    value: "skilled-labourer",
    label: "Skilled Labourer",
    baseRate: 32,
    hoursPerWeek: 40,
    kiwisaverPct: 0.03,
  },
  {
    value: "builder-carpenter",
    label: "Builder / Carpenter",
    baseRate: 38,
    hoursPerWeek: 40,
    kiwisaverPct: 0.03,
  },
  {
    value: "foreman",
    label: "Foreman",
    baseRate: 45,
    hoursPerWeek: 45,
    kiwisaverPct: 0.03,
  },
  {
    value: "site-supervisor",
    label: "Site Supervisor",
    baseRate: 48,
    hoursPerWeek: 45,
    kiwisaverPct: 0.03,
  },
  {
    value: "steel-fixer",
    label: "Steel Fixer",
    baseRate: 38,
    hoursPerWeek: 40,
    kiwisaverPct: 0.03,
  },
  {
    value: "formworker",
    label: "Formworker",
    baseRate: 38,
    hoursPerWeek: 40,
    kiwisaverPct: 0.03,
  },
  {
    value: "concrete-finisher",
    label: "Concrete Finisher",
    baseRate: 40,
    hoursPerWeek: 40,
    kiwisaverPct: 0.03,
  },
  {
    value: "machine-operator",
    label: "Machine Operator",
    baseRate: 42,
    hoursPerWeek: 45,
    kiwisaverPct: 0.03,
  },
  {
    value: "qs-admin",
    label: "QS / Admin",
    baseRate: 36,
    hoursPerWeek: 40,
    kiwisaverPct: 0.03,
  },
];